const $=s=>document.querySelector(s);
let peer=null,role='',localStream=null,roomId='',connections=new Map(),calls=new Map();
const status=t=>$('#status').textContent=t;
const connState=t=>$('#connectionState').textContent=t;
const countStudents=()=>{const n=role==='host'?[...connections.keys()].length:Math.max(0,[...connections.keys()].length);$('#studentCount').textContent=`تعداد دانش‌آموزان: ${n}`;};
function log(t,remote=false){const d=document.createElement('div');d.className='msg';d.textContent=(remote?'طرف مقابل: ':'شما: ')+t;$('#messages').appendChild(d);$('#messages').scrollTop=$('#messages').scrollHeight;}
function codeCopy(){const code=$('#myCode').textContent.trim();if(!code||code==='—')return status('ابتدا اتاق را بساز.');navigator.clipboard?.writeText(code).then(()=>status('کد اتاق کپی شد ✅')).catch(()=>{const ta=document.createElement('textarea');ta.value=code;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();status('کد اتاق کپی شد ✅');});}
$('#copyCodeBtn').onclick=codeCopy;
function videoCard(id,label,stream,muted=false){let c=document.getElementById('video-'+CSS.escape(id));if(!c){c=document.createElement('div');c.className='video-card';c.id='video-'+id;c.innerHTML='<video autoplay playsinline></video><span class="video-label"></span>';$('#videos').appendChild(c);}const v=c.querySelector('video');v.srcObject=stream;v.muted=muted;v.play().catch(()=>{});c.querySelector('.video-label').textContent=label;}
function removeVideo(id){document.getElementById('video-'+CSS.escape(id))?.remove();}
function broadcast(m,except=null){connections.forEach((x,id)=>{if(id!==except&&x.open)try{x.send(m)}catch(_){}});}
function setupConn(c){connections.set(c.peer,c);c.on('open',()=>{connState('متصل ✅');status('عضو جدید به کلاس وصل شد.');countStudents();c.send({type:'hello',from:peer.id,known:[...connections.keys()]});if(boardActions.length)c.send({type:'boardState',actions:boardActions,redo:redoActions});if(localStream)callPeer(c.peer);broadcast({type:'member',id:c.peer},c.peer);});c.on('data',m=>handleData(c.peer,m));c.on('close',()=>{connections.delete(c.peer);const call=calls.get(c.peer);try{call?.close()}catch(_){}calls.delete(c.peer);removeVideo(c.peer);countStudents();});c.on('error',e=>status('خطای اتصال: '+(e?.message||e)));countStudents();}
function connectTo(id){if(!id||id===peer?.id||connections.has(id))return;setupConn(peer.connect(id,{reliable:true,serialization:'json'}));}
function handleData(from,m){if(!m)return;if(m.type==='chat')log(m.text,true);if(m.type==='hello'){(m.known||[]).forEach(id=>{if(id!==peer.id)connectTo(id)});if(localStream)callPeer(from);}if(m.type==='member'&&m.id!==peer.id)connectTo(m.id);if(m.type==='boardState'){boardActions=m.actions||[];redoActions=m.redo||[];renderBoard();}if(m.type==='mute')updateRemoteLabel(from,m.muted);}
function updateRemoteLabel(id,muted){const c=document.getElementById('video-'+CSS.escape(id));if(c)c.querySelector('.video-label').textContent=(muted?'🔇 ':'')+'تصویر '+id;}
function callPeer(id){if(!localStream||!peer||id===peer.id||calls.has(id))return;const call=peer.call(id,localStream);calls.set(id,call);call.on('stream',s=>videoCard(id,'تصویر '+id,s));call.on('close',()=>{calls.delete(id);removeVideo(id)});call.on('error',()=>calls.delete(id));}
function answerCall(call){call.answer(localStream||undefined);calls.set(call.peer,call);call.on('stream',s=>videoCard(call.peer,'تصویر '+call.peer,s));call.on('close',()=>{calls.delete(call.peer);removeVideo(call.peer)});}
async function media(){try{if(!localStream)localStream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});videoCard('local','تصویر من',localStream,true);$('#mediaBtn').textContent='دوربین و میکروفون روشن است';connections.forEach((_,id)=>callPeer(id));status('دوربین و میکروفون روشن شد.');}catch(e){status('اجازه دوربین/میکروفون داده نشد: '+e.message);}}
$('#mediaBtn').onclick=media;
$('#muteBtn').onclick=()=>{const t=localStream?.getAudioTracks?.()[0];if(!t)return;t.enabled=!t.enabled;$('#muteBtn').textContent=t.enabled?'بی‌صدا کردن میکروفون':'روشن کردن میکروفون';broadcast({type:'mute',muted:!t.enabled});};
$('#camBtn').onclick=()=>{const t=localStream?.getVideoTracks?.()[0];if(!t)return;t.enabled=!t.enabled;$('#camBtn').textContent=t.enabled?'خاموش کردن دوربین':'روشن کردن دوربین';};
$('#sendBtn').onclick=()=>{const v=$('#chatInput').value.trim();if(!v)return;log(v);broadcast({type:'chat',text:v});$('#chatInput').value='';};$('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#sendBtn').click();});
function makePeer(id){if(peer)peer.destroy();peer=new Peer(id);peer.on('open',()=>{$('#myCode').textContent=id;roomId=id;});peer.on('connection',setupConn);peer.on('call',answerCall);peer.on('error',e=>status('خطای اتاق: '+e.type));}
$('#createBtn').onclick=()=>{role='host';const saved=localStorage.getItem('mehrFarazanRoomId')||('mehr-'+Math.random().toString(36).slice(2,8));localStorage.setItem('mehrFarazanRoomId',saved);makePeer(saved);status('اتاق آماده است؛ کد را برای همهٔ دانش‌آموزان بفرست.');connState('در انتظار دانش‌آموزان…');};
$('#joinBtn').onclick=()=>{const id=$('#roomInput').value.trim();if(!id)return status('کد اتاق را وارد کن.');role='guest';makePeer();peer.on('open',()=>{roomId=id;$('#myCode').textContent=id;connectTo(id);status('در حال ورود به کلاس…');connState('در حال اتصال…');});};

const canvas=$('#board'),ctx=canvas.getContext('2d'),color=$('#color'),size=$('#size');let boardActions=[],redoActions=[],tool='pen',drawing=false,start=null,preview=null;
function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));ctx.setTransform(d,0,0,d,0,0);ctx.fillStyle='#fff';ctx.fillRect(0,0,r.width,r.height);renderBoard();}resize();window.addEventListener('resize',resize);
function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
function shapePath(a){const{x,y,w,h}=a;ctx.beginPath();if(a.kind==='line'){ctx.moveTo(x,y);ctx.lineTo(x+w,y+h);}else if(a.kind==='rectangle'){ctx.rect(x,y,w,h);}else if(a.kind==='circle'){ctx.ellipse(x+w/2,y+h/2,Math.abs(w/2),Math.abs(h/2),0,0,Math.PI*2);}else if(a.kind==='triangle'){ctx.moveTo(x+w/2,y);ctx.lineTo(x,y+h);ctx.lineTo(x+w,y+h);ctx.closePath();}else if(a.kind==='arrow'){const ang=Math.atan2(h,w),hd=14;ctx.moveTo(x,y);ctx.lineTo(x+w,y+h);ctx.moveTo(x+w,y+h);ctx.lineTo(x+w-hd*Math.cos(ang-Math.PI/6),y+h-hd*Math.sin(ang-Math.PI/6));ctx.moveTo(x+w,y+h);ctx.lineTo(x+w-hd*Math.cos(ang+Math.PI/6),y+h-hd*Math.sin(ang+Math.PI/6));}}
function drawAction(a){ctx.save();ctx.setTransform(devicePixelRatio||1,0,0,devicePixelRatio||1,0,0);ctx.strokeStyle=a.color;ctx.lineWidth=a.size;ctx.lineCap='round';ctx.lineJoin='round';shapePath(a);ctx.stroke();ctx.restore();}
function renderBoard(){const d=devicePixelRatio||1,r=canvas.getBoundingClientRect();ctx.setTransform(d,0,0,d,0,0);ctx.fillStyle='#fff';ctx.fillRect(0,0,r.width,r.height);boardActions.forEach(drawAction);}
function broadcastBoard(){broadcast({type:'boardState',actions:boardActions,redo:redoActions});}
function commit(a){boardActions.push(a);redoActions=[];renderBoard();broadcastBoard();}
canvas.addEventListener('pointerdown',e=>{drawing=true;start=point(e);preview=null;canvas.setPointerCapture?.(e.pointerId);});
canvas.addEventListener('pointermove',e=>{if(!drawing||!start)return;const p=point(e);if(tool==='pen'){commit({kind:'line',x:start.x,y:start.y,w:p.x-start.x,h:p.y-start.y,color:color.value,size:Number(size.value)});start=p;return;}if(tool==='eraser'){const r=Number(size.value)*2;boardActions=boardActions.filter(a=>Math.abs((a.x+a.w/2)-p.x)>r||Math.abs((a.y+a.h/2)-p.y)>r);renderBoard();broadcastBoard();start=p;return;}preview={kind:tool,x:start.x,y:start.y,w:p.x-start.x,h:p.y-start.y,color:color.value,size:Number(size.value)};renderBoard();drawAction(preview);});
canvas.addEventListener('pointerup',e=>{if(!drawing||!start)return;const p=point(e);if(tool!=='pen'&&tool!=='eraser')commit({kind:tool,x:start.x,y:start.y,w:p.x-start.x,h:p.y-start.y,color:color.value,size:Number(size.value)});drawing=false;start=null;preview=null;renderBoard();});canvas.addEventListener('pointercancel',()=>{drawing=false;start=null;preview=null;renderBoard();});
document.querySelectorAll('.tool-btn[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('.tool-btn[data-tool]').forEach(x=>x.classList.remove('active'));b.classList.add('active');});
$('#clearBtn').onclick=()=>{boardActions=[];redoActions=[];renderBoard();broadcastBoard();};
$('#undoBtn').onclick=()=>{if(!boardActions.length)return;redoActions.push(boardActions.pop());renderBoard();broadcastBoard();};
$('#redoBtn').onclick=()=>{if(!redoActions.length)return;boardActions.push(redoActions.pop());renderBoard();broadcastBoard();};
