(()=>{
  const eraserBtn=document.querySelector('[data-tool="eraser"]');
  const canvas=document.querySelector('#board');
  const ctx=canvas?.getContext('2d');
  if(!eraserBtn||!canvas||!ctx)return;
  let eraserSize=22;
  const wrap=document.createElement('div');
  wrap.className='eraser-size-wrap';
  wrap.innerHTML='<button type="button" id="eraserSizeBtn" class="eraser-size-btn">📏 اندازه پاک‌کن</button>';
  eraserBtn.insertAdjacentElement('afterend',wrap);
  const modal=document.createElement('div');
  modal.id='eraserSizeModal';
  modal.className='eraser-size-modal hidden';
  modal.innerHTML='<div class="eraser-size-card"><button type="button" id="closeEraserSize" class="close">×</button><h3>اندازه پاک‌کن</h3><p id="eraserSizeValue">اندازه: 22 پیکسل</p><input id="eraserSizeRange" type="range" min="5" max="80" value="22" step="1"><div class="eraser-size-labels"><span>خیلی کوچک</span><span>متوسط</span><span>خیلی بزرگ</span></div><button type="button" id="saveEraserSize" class="primary">اعمال اندازه</button></div>';
  document.body.appendChild(modal);
  const range=modal.querySelector('#eraserSizeRange'),value=modal.querySelector('#eraserSizeValue');
  const updateLabel=()=>value.textContent=`اندازه: ${range.value} پیکسل`;
  const open=()=>{range.value=eraserSize;updateLabel();modal.classList.remove('hidden');};
  const close=()=>modal.classList.add('hidden');
  document.querySelector('#eraserSizeBtn').onclick=open;
  modal.querySelector('#closeEraserSize').onclick=close;
  modal.querySelector('#saveEraserSize').onclick=()=>{eraserSize=Number(range.value);updateLabel();close();};
  range.oninput=updateLabel;
  modal.addEventListener('click',e=>{if(e.target===modal)close();});
  canvas.addEventListener('pointerdown',()=>{if(document.querySelector('.tool[data-tool="eraser"].active'))ctx.lineWidth=eraserSize;},true);
  canvas.addEventListener('pointermove',()=>{if(document.querySelector('.tool[data-tool="eraser"].active'))ctx.lineWidth=eraserSize;},true);
  const style=document.createElement('style');
  style.textContent=`.eraser-size-wrap{margin:0 0 6px}.eraser-size-btn{width:100%;font-family:inherit;border:1px solid var(--line);border-radius:11px;padding:8px 10px;background:#fff;color:var(--ink);cursor:pointer}.eraser-size-btn:hover{background:#f7fbff}.eraser-size-modal{position:fixed;inset:0;background:rgba(12,35,56,.46);display:grid;place-items:center;z-index:50;padding:20px}.eraser-size-modal.hidden{display:none}.eraser-size-card{position:relative;width:min(430px,100%);background:#fff;border:1px solid var(--line);box-shadow:var(--shadow);border-radius:22px;padding:28px}.eraser-size-card h3{margin:0 0 8px;font-size:23px}.eraser-size-card p{margin:0 0 18px;color:var(--muted);font-weight:700}#eraserSizeRange{width:100%;accent-color:var(--primary);cursor:pointer}.eraser-size-labels{display:flex;justify-content:space-between;color:var(--muted);font-size:12px;margin:5px 0 18px}#saveEraserSize{width:100%}`;
  document.head.appendChild(style);
})();
